### ISSUE TITLE
Bookmarks menu isn't loading since 1.0.1 update

### ISSUE THREAD

**Issue by akrherz** [igniterealtime/openfire-bookmarks-plugin#6]
...Migrated from [Ignite Jira 1662](https://issues.igniterealtime.org/browse/OF-1662)...

Since Bookmarks 1.0.1 update clicking on Bookmarks menu shows blank page. See no related errors in the log.

**Comment by wrooot** [comment]
Same with 4.2.3 and 4.3.0 beta.

**Comment by GregDThomas** [comment]
Probably due to errors in pom.xml that mean the JSPs are not pre-compiled. There's a difference between 
https://github.com/igniterealtime/openfire-bookmarks-plugin/blob/master/pom.xml (not working) and
https://github.com/igniterealtime/openfire-xmldebugger-plugin/blob/master/pom.xml (working)

**Comment by akrherz** [comment]
PR is in with release 1.0.2
