### ISSUE TITLE
Fix Maven build

### ISSUE THREAD

**Issue by wrooot** [igniterealtime/openfire-bookmarks-plugin#9]
To build plugins for Openfire 4.3.0 pom.xml should include repositories tags pointing to Archiva. If plugin has pages in Admin Console, web.xml should also be added.

For references:
https://github.com/igniterealtime/openfire-clientControl-plugin/pull/11

**Comment by GregDThomas** [comment]
Fixed in https://github.com/igniterealtime/openfire-bookmarks-plugin/pull/10 - but can't explain why it's not building right now.

**Comment by GregDThomas** [comment]
Oh, the merge took. Can't pretend to understand what's going on, but happy it's OK.
